version: "2"
services:
    sonarqube:
        image: sonarqube
        ports:
            - 9000:9000
        volumes:
            - ./sonar.properties:/opt/sonarqube/conf/sonar.properties
            - .var/sonarqube/data:/opt/sonarqube/data
            - .var/sonarqube/logs:/opt/sonarqube/logs
            - .var/sonarqube/extensions:/opt/sonarqube/extensions
