version: '3'
services:
    sonarqube:
        image: sonarqube
        ports: 
            - 9000:9000
        volumes: 
            - ~/docker/sonarqube/sonar.properties:/opt/sonarqube/conf/sonar.properties
            - ~/containers/sonarqube/data:/opt/sonarqube/data
            - ~/containers/sonarqube/logs:/opt/sonarqube/logs
            - ~/containers/sonarqube/extensions:/opt/sonarqube/extensions