services:
  mock-server:
    image: mockserver/mockserver:latest
    ports:
      - 1080:1080
    environment:
      MOCKSERVER_PROPERTY_FILE: ./config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: ./config/initializerJson.json
    volumes:
      - type: bind
        source: ./config
        target: /config
    networks:
      - mock-server-network
  nginx:
    image: nginx:latest
    ports:
      - 2080:80
    volumes:
      - type: bind
        source: ./config/nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - mock-server
    networks:
      - mock-server-network

networks:
  mock-server-network:
    driver: bridge
