version: "2"
services:
  mock-server:
    image: mockserver/mockserver:latest
    ports:
      - 1080:1080
    environment:
      MOCKSERVER_PROPERTY_FILE: ./config/mockserver.properties
      MOCKSERVER_WATCH_INITIALIZATION_JSON: 'TRUE'
      MOCKSERVER_INITIALIZATION_JSON_PATH: ./config/initializerJson.json
    volumes:
      - type: bind
        source: ./config
        target: /config
