version: '2'
services: 
    mysql:
        image: mysql:8
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment: 
            MYSQL_USER: herik
            MYSQL_PASSWORD: mysql
            MYSQL_ROOT_PASSWORD: mysql
        ports: 
            - 3306:3306
        networks: 
            - mysql_network
        volumes: 
            - .var/data:/var/lib/mysql
networks: 
    mysql_network:
