version: '2'
services: 
    mysql:
        image: mysql:8
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment: 
            MYSQL_USER: herik
            MYSQL_PASSWORD: mysql
            MYSQL_ROOT_PASSWORD: mysql
        ports: 
            - 3306:3306
        networks: 
            - mysql_network
        volumes: 
            - ~/containers/mysql/data:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment: 
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: mysql
            MYSQL_USER: herik
            MYSQL_PASSWORD: mysql
        networks: 
            - mysql_network
        ports: 
            - 1000:80
networks: 
    mysql_network:
