version: "2"
services:
    postgres:
        image: postgres:latest
        container_name: postgres
        volumes:
            - .var/data:/var/lib/postgresql/data
            - .var/conf:/etc/postgresql/postgresql.conf
        environment:
            POSTGRES_PASSWORD: postgres
        ports:
            - 5432:5432
        networks:
            - postgres_network
networks:
    postgres_network:
