version: '3'

services:
  mongo:
    image: mongo
    container_name: mongodb
    networks:
      - global-default
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
networks:
  global-default:
    external: true
